import { defaultTheme, palette } from 'practical-react-components-core'
  export const myCustomTheme =  {
  ...defaultTheme,
  name: 'customTheme',
  color: {
text00:palette.white,
text01:palette.grey16,
text02:palette.grey24,
text03:palette.grey32,
text04:palette.grey40,
text05:palette.grey48,
text06:palette.grey16,
textLink:palette.lightBlue700,
textLinkHover:palette.lightBlue700,
textPrimary:palette.lightBlue700,
textError:palette.red700,
background:palette.white,
background00:palette.white,
background01:palette.grey94,
background02:palette.grey96,
background03:palette.grey98,
background04:palette.grey98,
background05:palette.white,
backgroundPrimary:palette.grey96,
backgroundError:palette.red50,
element01:palette.grey40,
element10:palette.grey98,
element11:palette.grey80,
element12:palette.grey90,
element13:palette.grey72,
element14:palette.grey64,
element15:palette.grey98,
element16:palette.grey98,
elementPrimary:palette.lightBlueA700,
elementHalfPrimary:palette.lightBlueA700,
elementError:palette.red700,
elementSuccess:palette.green700,
elementWarning:palette.amber500,
elementAccent:palette.deepPurple500,
elementBorder:palette.transparent,
}
}