#!/bin/sh

    echo "Starting Service"
    chmod 777 /usr/local/packages/Tailscale_VPN_Auto_Update/lib/tailscale
    chmod 777 /usr/local/packages/Tailscale_VPN_Auto_Update/lib/tailscaled
    /usr/local/packages/Tailscale_VPN_Auto_Update/lib/tailscaled &
    echo "Service Started"
    echo "Scroll to Bottom for link"
    /usr/local/packages/Tailscale_VPN_Auto_Update/lib/tailscale up
    /usr/local/packages/Tailscale_VPN_Auto_Update/lib/tailscale set --auto-update
    wait