#!/bin/sh

    echo "Starting Service"
    chmod 777 /usr/local/packages/Tailscale_VPN/lib/tailscale
    chmod 777 /usr/local/packages/Tailscale_VPN/lib/tailscaled
    /usr/local/packages/Tailscale_VPN/lib/tailscaled &
    echo "Service Started"
    echo "Scroll to Bottom for link"
    /usr/local/packages/Tailscale_VPN/lib/tailscale up
    wait